print('You can get a Rock at level 1.\n')
print('You can get a Pogo Stick at level 1.\n')
print('You can get a Wand at level 2\n')
print('You can get a Pogo Stick at level 2.\n')
print('You can get a Wand at level 3.\n')
print('You can get a Rock at level 3.\n')
print('You can get a Pogo Stick at level 3\n')